### ISSUE TITLE
time display in records list

### ISSUE THREAD

**Issue by japonicus** [NERC-CEH/NYPH-app#24]
depends on #5

Rather than displaying dates in the record list should try to display friendly time and/or date (but time only for records that have gps fix - as these are the only one that can be assumed to be entered live in the field.

**Comment by kazlauskis** [comment]
Will it not be confusing why some records show a full timestamp while others don't?

**Comment by japonicus** [comment]
Not too bad.

For a typical user on the 1st Jan I'd expect a list to look something like

today, 09:36
today, 09:40
today                         (where for some reason this record wasn't
gps'ed - so stamp is less trusted
today, 09:52

(if we were clever we might be able to safely infer that the record between
09:40 and 09:52 also has a trusted stamp)

if viewed later the list would look like

1/1/2017 09:36
1/1/2017 09:40
1/1/2017
1/1/2017 09:52
